### ISSUE TITLE
Question about the use of /40/

### ISSUE THREAD

**Issue by ThomasOF93** [swico/www.swiss-qr-invoice.org#39]
Hello everyone

If a discount is provided for an invoice. Can the document date be defined via /11/ and the conditions like /40/.

Is it ensured that when processing such an invoice, the discount is taken into account or not, depending on the current date. Does the amount have to be changed manually or does this happen automatically?

In the example below, the automatic discount deduction does not work. Was something misconfigured?

Thank you very much and kind regards

![Beispielrechnung](https://github.com/swico/www.swiss-qr-invoice.org/assets/159114874/8649ae5c-1243-4591-9d62-0e79bb6c1773)

**Comment by epsitec** [comment]
Hi Thomas

Your invoice is perfectly valid. I uploaded it to https://swiss-qr-invoice.org/validator and this is what I get back:

![image](https://github.com/swico/www.swiss-qr-invoice.org/assets/3872435/a57ad4fa-d986-4738-8935-f23606671c52)

It is up to the software which manages the payment to take into account the specified discount and suggest a 2% reduction if the payment is done before the 30-day payment period expires. Don't expect an e-banking portal or m-banking solution to honor this information, though.

**Comment by nicolasguillet** [comment]
I agree with Pierre. If you received this invoice, ask your software vendor to implement such a discount functionality, otherwise, ask your customer to do so with their software vendor.
No bank as of now even look at the due date given by the info in /40/, so I don’t think any bank will anytime soon offer such a feature. (Some say, that’s for legal reasons.)
In both cases, it’s the customers of the software vendors and the banks who would profit from this. So, it’s even harder to understand, why this isn’t a widespread feature yet.
For the ebill functionality in most banks, it is up to SIX to provide such a feature, but that requires the stakeholders of SIX (the banks) to push this, or at least to agree with it.
